// Generated by Finicky Kickstart 
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: "Firefox",      
  handlers: [
    {
      match: /^https:\/\/esa38804\.live\.dynatrace\.com\/.*$/,
      browser: "Brave Browser"
    },
    {
      match: /^https:\/\/jira\.photobox\.com\/$/,
      browser: "Brave Browser"
    },
    {
      match: /^https:\/\/github\.com\/$/,
      browser: "Firefox"
    }
  ]
}
